agenda = open("/home/yulienis/DEV/aprendopython/4/agendatelefonica.csv")
#print(agenda.read())
print(agenda.readline())
print(agenda.readline())
print(agenda.readline())
print(agenda.readline())
print(agenda.readline())