#print("Operadores Matematicos")
#print("si escrivo las oraciones matematicas entre comillas, no me mostrara el resultado, sino que lo escrivira como texto, por lo que se debe escribir solo entre parentesis ()")
#print("Ejemplo")
#print("3+3+4+5")
print(3+3+4+5)
print(3+3+4+5)
print(3*3)
print(8-4+1)
print(2*4+2-3)
print(9/3)
#print("el operador matematiico porciento(%) te calcula el resto de la divicion, a continuacion dos ejemplo")
print(9%2)
print(10%4)
print(5-8)
#print("Operadores logicos")
#print("Estos no devuelven un valor numerico como resultado, sino una validacion verdadera o falsa")
##print(3>2)
##print(3 <= 5)
##print(5==5)
##print(5==6)
#print(7!=7)
#print(5==4)
print(5==5 and 4==4 and 6==6)
